# Neural Network Programming – Deep Learning with PyTorch

Link: http://deeplizard.com/learn/video/v5cngxo4mIg

# PyTorch Explained - Python Deep Learning Neural Network API

Link: http://deeplizard.com/learn/video/iTKbyFh-7GM

PyTorch is a python package that provides two high-level features:

- Tensor computation (like numpy) with strong GPU acceleration
- Deep Neural Networks built on a tape-based autodiff system

# PyTorch Install – Quick and Easy

Link: http://deeplizard.com/learn/video/UWlFM0R_x6I

## Verify the PyTorch install

In [2]:
import torch

In [3]:
print(torch.__version__)

1.1.0


In [4]:
torch.cuda.is_available()

True

In [5]:
torch.version.cuda

'9.0'

# CUDA Explained – Why Deep Learning Uses GPUs

Link: http://deeplizard.com/learn/video/6stDhEA0wFQ

In [6]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [7]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

In [9]:
t = t.cpu()
t

tensor([1, 2, 3])

# Tensors Explained – Data Structures of Deep Learning

## Indexes

In [10]:
a = [1,2,3,4]

In [11]:
a[2]

3

In [12]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [13]:
dd[0][2]

3

## Rank, Axes, and Shape Explained – Tensors for Deep Learning

## Rank

A tensor's *rank* tells us how many indexes are needed to refer to a specific element within the tensor.

## Axes

In [14]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [15]:
dd[0]

[1, 2, 3]

In [16]:
dd[1]

[4, 5, 6]

In [17]:
dd[2]

[7, 8, 9]

The first index of axis 2:

In [18]:
dd[0][0]

1

In [19]:
dd[1][0]

4

In [20]:
dd[2][0]

7

The second index of axis 2:

In [21]:
dd[0][1]

2

In [22]:
dd[1][1]

5

In [23]:
dd[2][1]

8

The third index of axis 3:

In [24]:
dd[0][2]

3

In [25]:
dd[1][2]

6

In [26]:
dd[2][2]

9

## Shape

In [27]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [28]:
t = torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [29]:
type(t)

torch.Tensor

In [38]:
t.shape

torch.Size([3, 3])

In [32]:
t.size()

torch.Size([3, 3])

A tensor's shape is important:

In [33]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [34]:
t.reshape(1,9).shape

torch.Size([1, 9])

# PyTorch Tensors Explained - Neural Network Programming

In [40]:
import torch
import numpy as np

## Tensor class

Tensors in PyTorch are represented using the ```torch.Tensor``` class. 

In [61]:
t = torch.Tensor()

## Tensor attributes

In [57]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [58]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

## Creation options using data

In [59]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [51]:
o1 = torch.Tensor(data)
o1

tensor([1., 2., 3.])

In [54]:
o2 = torch.tensor(data)
o2

tensor([1, 2, 3], dtype=torch.int32)

In [55]:
o3 = torch.as_tensor(data)
o3

tensor([1, 2, 3], dtype=torch.int32)

In [56]:
o4 = torch.from_numpy(data)
o4

tensor([1, 2, 3], dtype=torch.int32)

## Creation options without data

In [62]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [63]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [64]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [65]:
torch.rand(2,2)

tensor([[0.7081, 0.1972],
        [0.8002, 0.4517]])

## Creating PyTorch Tensors – Best Options

In [66]:
import torch
import numpy as np

In [67]:
data = np.array([1,2,3])

In [68]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [69]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [70]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


The constructor function used the default dtype.

In [71]:
torch.get_default_dtype()

torch.float32

In [72]:
t1.dtype == torch.get_default_dtype()

True

The factory functions infer the dtype.

In [73]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3], dtype=torch.int32)

In [74]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

The dtype can be explicitly set.

In [75]:
torch.tensor(np.array([1,2,3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

## Memory: Sharing vs Copying

In [82]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [83]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [84]:
data[0] = 0
data[1] = 0
data[2] = 0

In [85]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [86]:
print(t3)
print(t4)

tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


In [87]:
n1 = t1.numpy()

In [88]:
n1

array([1., 2., 3.], dtype=float32)

In [89]:
n1[0] = 0
n1[1] = 0
n1[2] = 0

In [90]:
n1

array([0., 0., 0.], dtype=float32)

In [91]:
t1

tensor([0., 0., 0.])

In [99]:
l = [1,2,3,4]
t = torch.as_tensor(l)
l[1] = 0
print(t)

tensor([1, 2, 3, 4])


# Tensor Operations for Deep Learning

Operations by category:
- Reshaping ops
- Element-wise ops
- Reduction ops
- Access ops


## Reshaping Explained - PyTorch Tensors for Deep Learning

In [100]:
import torch

In [101]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [102]:
t.size()

torch.Size([3, 4])

In [103]:
t.shape

torch.Size([3, 4])

In [104]:
len(t.shape)

2

In [105]:
torch.tensor(t.shape).prod()

tensor(12)

In [106]:
t.numel()

12

In [107]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [108]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [109]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [110]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [111]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [112]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [113]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [114]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [115]:
print(t.view(1,12))
print(t.view(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [116]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [117]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [118]:
print(t.size())

torch.Size([3, 4])


In [119]:
print(t.reshape(1, 12).squeeze().shape)

torch.Size([12])


In [121]:
print(t.reshape(12,).shape)

torch.Size([12])


In [120]:
print(t.unsqueeze(dim=0).shape)

torch.Size([1, 3, 4])


In [ ]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [ ]:
flatten(t)

In [ ]:
t.reshape(-1)

## Reshaping Explained - PyTorch Tensors for Deep Learning

In [122]:
import torch

### Shape/Size of a tensor

In [123]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [124]:
t.size()

torch.Size([3, 4])

In [125]:
t.shape

torch.Size([3, 4])

In [126]:
len(t.shape)

2

In [127]:
torch.tensor(t.shape).prod()

tensor(12)

In [128]:
t.numel()

12

Since our tensor ```t``` has 12 elements, any reshaping must account for the number of elements (```12```). 

### Reshape/View

In [129]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [130]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [131]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [132]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [133]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [134]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

Reshaping and changing the rank.

In [135]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

### Squeeze/Unsqueeze

In [136]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [137]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [138]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


Here is a use case for squeeze:

In [139]:
def flatten(t):
    t = t.reshape(1, -1)
    t = t.squeeze()
    return t

In [140]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

### Concantenate two tensors

In [141]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [144]:
torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [145]:
torch.cat((t1, t2), dim=0).shape

torch.Size([4, 2])

In [146]:
torch.cat((t1, t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [147]:
torch.cat((t1, t2), dim=1).shape

torch.Size([2, 4])

## CNN Flatten Operation Visualized – Tensor Batch Processing for Deep Learning

In [148]:
import torch

In [149]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [150]:
t = torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

In [151]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

Add the color channel axis so we'll have: `(Batch size, Color channels, Height, Width)`

In [152]:
t = t.reshape(3,1,4,4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [153]:
t[0]

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [154]:
t[0][0]

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [155]:
t[0][0][0]

tensor([1, 1, 1, 1])

In [156]:
t[0][0][0][0]

tensor(1)

### Shout outs for alternative implementations of the `flatten()`s function!

In [157]:
t.reshape(1,-1)[0] # Thank you Mick!

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [158]:
t.reshape(-1) # Thank you Aamir!

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [159]:
t.view(t.numel()) # Thank you Ulm!

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [160]:
t.flatten() # Thank you PyTorch!

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

### Only Flatten the last 3 axes

In [161]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [162]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

## Element-wise tensor operations - Deep Learning and Neural Networks

Element-wise means that we operate on corresponding elements.  
Two elements are said to corresponding if the two elements occupy the same position within the tensor.  
The position is determined by the indexes used to specify a given element.

In [163]:
import torch
import numpy as np

In [164]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

In [165]:
# Example from the first axis
t1[0]

tensor([1., 2.])

In [166]:
# Example from the second axis
t1[0][0]

tensor(1.)

In [167]:
t1[0][0]

tensor(1.)

In [168]:
t2[0][0]

tensor(9.)

### Addition is an element-wise operation

In [169]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]])

### Arithmetic operations are element-wise operations

Let's see how we can add scalar values to tensors:

In [170]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

In [171]:
t1 - 2

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [172]:
t1 * 2

tensor([[2., 4.],
        [6., 8.]])

In [173]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [174]:
t1.add(2)

tensor([[3., 4.],
        [5., 6.]])

In [175]:
t1.sub(2)

tensor([[-1.,  0.],
        [ 1.,  2.]])

In [176]:
t1.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [177]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

These examples make it look like element-wise means *for each element*.  
However, this is misleading.  
A concept called broadcasting is being used here.

#### Broadcasting tensors

What is really happening in ```t1 + 2``` is that the scaler ```2``` is being broadcasted to the shape of ```t1```.  
This can be done using Numpy like this:

In [178]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

After the new tensor is created from the broadcast operation, the element-wise addition is performed.  
So this:

In [179]:
t1 + 2

tensor([[3., 4.],
        [5., 6.]])

is really this:

In [180]:
t1 + torch.tensor(
    np.broadcast_to(2, t1.shape)
    ,dtype=torch.float32
)

tensor([[3., 4.],
        [5., 6.]])

Trickier example:

In [181]:
t1 = torch.tensor([
    [1,1],
    [1,1]
], dtype=torch.float32)

t2 = torch.tensor([2,4], dtype=torch.float32)

In [182]:
# t1 + t2 ???????

In [183]:
t1.shape

torch.Size([2, 2])

In [184]:
t2.shape

torch.Size([2])

In [185]:
np.broadcast_to(t2.numpy(), t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [186]:
t1 + t2

tensor([[3., 5.],
        [3., 5.]])

See this one for a deeper discussion on broadcasting: http://deeplizard.com/learn/video/6_33ulFDuCg

### Element-wise comparison operations

In [187]:
t = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

In [188]:
t.eq(0)

tensor([[1, 0, 0],
        [0, 1, 0],
        [1, 0, 1]], dtype=torch.uint8)

In [189]:
t.ge(0)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)

In [190]:
t.gt(0)

tensor([[0, 1, 1],
        [1, 0, 1],
        [0, 1, 0]], dtype=torch.uint8)

In [191]:
t.lt(0)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)

In [192]:
t.le(7)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 0, 1]], dtype=torch.uint8)

Thinking about these types of operations from a broadcasting perspective, we can see that ```t.le(7)``` is the same thing as:

In [193]:
t <= torch.tensor(
    np.broadcast_to(7, t.shape)
    ,dtype=torch.float32
)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 0, 1]], dtype=torch.uint8)

In [195]:
t <= 7

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 0, 1]], dtype=torch.uint8)

and this:

In [196]:
t <= torch.tensor([
    [7,7,7],
    [7,7,7],
    [7,7,7]
], dtype=torch.float32)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 0, 1]], dtype=torch.uint8)

### Element-wise operations using functions

In [197]:
t.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [198]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [199]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [200]:
t.neg().abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

## Argmax and Reduction Ops - Tensors for Deep Learning

In [201]:
import torch
import numpy as np

A tensor *reduction operation* is an operation that reduces the number of elements contained within a given tensor. 

Suppose we have the following tensor:

In [202]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

Observe that the sum function returns the sum of all the elements in the tensor:

In [203]:
t.sum()

tensor(8.)

In [204]:
t.numel()

9

In [205]:
t.sum().numel()

1

In [206]:
t.sum().numel() < t.numel()

True

Therefore, we can conclude that the ```sum()``` function is a reduction operation.

### Common reduction operations

In [207]:
t.sum()

tensor(8.)

In [208]:
t.prod()

tensor(0.)

In [209]:
t.mean()

tensor(0.8889)

In [210]:
t.std()

tensor(1.1667)

### Reduce specific axes

In [211]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [212]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [213]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

Element-wise opeartions are in play here:

In [214]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [215]:
t[0]

tensor([1., 1., 1., 1.])

In [216]:
t[1]

tensor([2., 2., 2., 2.])

In [217]:
t[2]

tensor([3., 3., 3., 3.])

In [218]:
t[0] + t[1] + t[2]

tensor([6., 6., 6., 6.])

Three groups of four:

In [219]:
t[0].sum()

tensor(4.)

In [220]:
t[1].sum()

tensor(8.)

In [221]:
t[2].sum()

tensor(12.)

In [222]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

### Max/Argmax

In [223]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [224]:
t.max()

tensor(5.)

In [225]:
t.argmax()

tensor(11)

In [226]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

If we specify a dimension, the ```max()``` function will return two tensors.  

In [227]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [228]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [229]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 2, 3]))

In [230]:
t.argmax(dim=1)

tensor([3, 2, 3])

## Accessing operations

In [232]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

In [233]:
t.mean()

tensor(5.)

In [234]:
t.mean().item()

5.0

In [235]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [236]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)